app:
  show_version_update: true
  version_check_url: https://raw.githubusercontent.com/sansan0/TrendRadar/refs/heads/master/version
crawler:
  default_proxy: http://127.0.0.1:10086
  enable_crawler: true
  request_interval: 1000
  use_proxy: false
notification:
  batch_send_interval: 1
  enable_notification: true
  feishu_message_separator: ━━━━━━━━━━━━━━━━━━━
  message_batch_size: 4000
  webhooks:
    dingtalk_url: ''
    feishu_url: https://www.feishu.cn/flow/api/trigger-webhook/
    telegram_bot_token: ''
    telegram_chat_id: ''
    wework_url: ''
platforms:
- enabled: true
  id: toutiao
  name: 今日头条
- enabled: true
  id: baidu
  name: 百度热搜
- enabled: true
  id: wallstreetcn-hot
  name: 华尔街见闻
- enabled: true
  id: thepaper
  name: 澎湃新闻
- enabled: true
  id: bilibili-hot-search
  name: bilibili 热搜
- enabled: true
  id: cls-hot
  name: 财联社热门
- enabled: true
  id: ifeng
  name: 凤凰网
- enabled: true
  id: tieba
  name: 贴吧
- enabled: true
  id: weibo
  name: 微博
- enabled: true
  id: douyin
  name: 抖音
- enabled: true
  id: zhihu
  name: 知乎
- enabled: true
  id: 36kr
  name: 36氪
- enabled: false
  id: coolapk
  name: 酷安
- enabled: true
  id: cankaoxiaoxi
  name: 参考消息
- enabled: false
  id: chongbuluo
  name: 虫部落
- enabled: false
  id: fastbull
  name: 快牛财经
- enabled: false
  id: gelonghui
  name: 格隆汇
- enabled: true
  id: github
  name: GitHub Trending
- enabled: true
  id: hackernews
  name: Hacker News
- enabled: false
  id: hupu
  name: 虎扑
- enabled: false
  id: ithome
  name: IT之家
- enabled: false
  id: jin10
  name: 金十数据
- enabled: true
  id: juejin
  name: 掘金
- enabled: false
  id: kaopu
  name: 靠谱新闻
- enabled: false
  id: kuaishou
  name: 快手
- enabled: false
  id: linuxdo
  name: Linux.do
- enabled: false
  id: mktnews
  name: 市场资讯
- enabled: false
  id: nowcoder
  name: 牛客网
- enabled: false
  id: pcbeta
  name: 远景论坛
- enabled: false
  id: producthunt
  name: Product Hunt
- enabled: true
  id: smzdm
  name: 什么值得买
- enabled: false
  id: solidot
  name: 奇客资讯
- enabled: false
  id: sputniknewscn
  name: 俄罗斯卫星通讯社
- enabled: false
  id: sspai
  name: 少数派
- enabled: false
  id: v2ex
  name: V2EX
- enabled: true
  id: xueqiu
  name: 雪球
- enabled: true
  id: zaobao
  name: 联合早报
report:
  mode: incremental
  rank_threshold: 5
weight:
  frequency_weight: 0.3
  hotness_weight: 0.1
  rank_weight: 0.6
